apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: go-web-app
spec:
  ingressclass: nginx
  rules:
  - host: go-web-app.local
    http:
      paths:
      - backend:
          service:
            name: go-web-app
            port:
              number: 8080
        path: /
        pathType: Exact
status:
  loadBalancer: {}
