apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-web-app
  name: go-web-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: go-web-app
status:
  loadBalancer: {}
