name: go-web-app-CI-CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup GO
      uses: actions/setup-go@v4
      with: 
        go-version: '1.23'
    - name: Build
      run: go build -o go-web-app
    - name: Testing
      run: go test ./...
      
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1
      with:
        install-mode: binary
        only-new-issues: false
        skip-cache: false
        skip-save-cache: false
        problem-matchers: false
        cache-invalidation-interval: 7
  push:
    runs-on: ubuntu-latest
    needs: [build, code-quality]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_PATELAUM }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push action
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_PATELAUM }}/go-web-app:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
    - name: Commit and push changes
      run: |
        git config --global user.email "techtv49@gmail.com"
        git config --global user.name "patel_aum"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "ACTIONS - Update tag in Helm chart"
        git push
